version: '3'

tasks:
  build:
    cmds:
      - go fmt
      - go build -v -o supersense cmd/*

  start:
    cmds:
      - task: build
      - ./supersense

  start-docker:
    - docker build -t ss:dev .
    - docker run --env-file=.env -p 8080:8080 --net=host ss:dev

  publish:
    cmds:
      - docker build -t minskylab/supersense .
      - docker push minskylab/supersense