version: "3"

tasks:
  build:
    cmds:
      - go fmt
      - go build -v -o supersense cmd/*

  build-observer:
    dir: observer
    cmds:
      - yarn build

  start-observer:
    dir: observer
    cmds:
      - yarn dev

  start-docker:
    - docker build -t ss:dev .
    - docker run --env-file=.env -p 8080:8080 --net=host ss:dev

  start:
    cmds:
      - task: build-observer
      - task: build
      - ./supersense

  publish:
    cmds:
      - task: build-observer
      - docker build -t minskylab/supersense .
      - docker push minskylab/supersense
