# This example assume that you have:
# 1. A secret with your supersense configuration (see README)
# 2. An ingress controller (could be traefik)
# 3. Certmanager service available in your cluster


config:
  secretRef: supersense-secret

service:
  type: ClusterIP
  port: 8080
  
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: supersense-demo.dev.minsky.cc
      paths:
        - "/"
  tls:
    - secretName: supersense-demo.dev.minsky.cc-cert
      hosts:
        - supersense-demo.dev.minsky.cc

# to install only runs:
# $ helm install <your-realease-name> minsky/supersense -f values.yaml